// app/sitemap.js — Sitemap index
// Auto-generated by scripts/generate-sitemap.mjs
export const dynamic = "force-dynamic";
export const runtime = "nodejs";

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || "https://visa.eammu.com";

const CHUNKS = [
  "static",
  "pairs-0", "pairs-1",
  "guides-0", "guides-1", "guides-2", "guides-3", "guides-4", "guides-5", "guides-6", "guides-7", "guides-8",
];

export default function sitemap() {
  return CHUNKS.map((id) => ({
    url: `${SITE_URL}/sitemap/${id}`,
    lastModified: new Date(),
  }));
}
