#!/usr/bin/env node
// generate-sitemap.mjs
// Run: node generate-sitemap.mjs
// Creates the full sitemap folder structure inside your Next.js app/

import fs from "fs";
import path from "path";

// ── Config ────────────────────────────────────────────────────────────────────
const APP_DIR = path.resolve("app"); // change if your app dir is different
const SITEMAP_DIR = path.join(APP_DIR, "sitemap");

const PAIR_CHUNKS  = [0, 1];
const GUIDE_CHUNKS = [0, 1, 2, 3, 4, 5, 6, 7, 8];

// ── Helpers ───────────────────────────────────────────────────────────────────
function write(filePath, content) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, "utf8");
  console.log("  wrote:", filePath.replace(process.cwd() + "/", ""));
}

// ── 1. app/sitemap.js  (index) ────────────────────────────────────────────────
const sitemapIndex = `// app/sitemap.js — Sitemap index
// Auto-generated by scripts/generate-sitemap.mjs
export const dynamic = "force-dynamic";
export const runtime = "nodejs";

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || "https://yoursite.com";

const CHUNKS = [
  "static",
  ${PAIR_CHUNKS.map(n => `"pairs-${n}"`).join(", ")},
  ${GUIDE_CHUNKS.map(n => `"guides-${n}"`).join(", ")},
];

export default function sitemap() {
  return CHUNKS.map((id) => ({
    url: \`\${SITE_URL}/sitemap/\${id}\`,
    lastModified: new Date(),
  }));
}
`;
write(path.join(APP_DIR, "sitemap.js"), sitemapIndex);

// ── 2. app/sitemap/_shared.js ────────────────────────────────────────────────
const shared = `// app/sitemap/_shared.js
// Auto-generated by scripts/generate-sitemap.mjs
// All sitemap logic lives here — route files just call handleChunk()

import { NextResponse } from "next/server";

export const SITE_URL   = process.env.NEXT_PUBLIC_SITE_URL || "https://yoursite.com";
const        API_BASE   = "https://api.eammu.com/api/v1";
const        API_KEY    = process.env.EAMMU_API_KEY;
export const CHUNK_SIZE = 50000;

export const GUIDE_SLUGS = [
  "visa-required",
  "e-visa",
  "visa-on-arrival",
  "eta",
  "visa-free",
  "no-admission",
];

export function slugify(str) {
  return (str || "").toLowerCase().replace(/\\s+/g, "-").replace(/[^a-z0-9-]/g, "");
}

// ── Fetch countries (Vercel edge-cached 24h) ──────────────────────────────────
export async function fetchCountries() {
  try {
    const res = await fetch(\`\${API_BASE}/countries?api_key=\${API_KEY}\`, {
      next: { revalidate: 86400 },
    });
    if (!res.ok) return [];
    const data = await res.json();
    return data.countries || [];
  } catch {
    return [];
  }
}

// ── Build pairs (module-level cache — computed once per cold start) ────────────
let _pairsCache = null;
export function buildAllPairs(countries) {
  if (_pairsCache) return _pairsCache;
  const pairs = [];
  for (const passport of countries) {
    for (const destination of countries) {
      if (passport.code === destination.code) continue;
      pairs.push(
        \`\${slugify(passport.country)}-visa-for-\${slugify(destination.country)}\`
      );
    }
  }
  _pairsCache = pairs;
  return pairs;
}

// ── XML builder ───────────────────────────────────────────────────────────────
function buildXml(urls) {
  const items = urls
    .map(
      (u) =>
        \`  <url>\\n    <loc>\${u.url}</loc>\\n    <lastmod>\${u.lastModified}</lastmod>\\n    <changefreq>\${u.changeFrequency}</changefreq>\\n    <priority>\${u.priority}</priority>\\n  </url>\`
    )
    .join("\\n");
  return \`<?xml version="1.0" encoding="UTF-8"?>\\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\\n\${items}\\n</urlset>\`;
}

function entry(url, priority = 0.6, changeFrequency = "weekly") {
  return {
    url,
    lastModified: new Date().toISOString().split("T")[0],
    changeFrequency,
    priority,
  };
}

// ── Universal chunk handler ───────────────────────────────────────────────────
export async function handleChunk(chunkId) {
  const countries = await fetchCountries();
  if (!countries.length) {
    return new NextResponse("<!-- API unavailable -->", {
      status: 503,
      headers: { "Content-Type": "application/xml" },
    });
  }

  const allPairs = buildAllPairs(countries);
  let urls = [];

  // static
  if (chunkId === "static") {
    urls = [
      entry(\`\${SITE_URL}\`,               1.0, "daily"),
      entry(\`\${SITE_URL}/visa-checker\`,  0.9, "daily"),
    ];
  }

  // pairs-N
  const pairsMatch = chunkId.match(/^pairs-(\\d+)$/);
  if (pairsMatch) {
    const n = parseInt(pairsMatch[1], 10);
    urls = allPairs
      .slice(n * CHUNK_SIZE, (n + 1) * CHUNK_SIZE)
      .map((cs) => entry(\`\${SITE_URL}/visa-checker/\${cs}\`, 0.7));
  }

  // guides-N
  const guidesMatch = chunkId.match(/^guides-(\\d+)$/);
  if (guidesMatch) {
    const n = parseInt(guidesMatch[1], 10);
    const all = [];
    for (const cs of allPairs) {
      for (const gs of GUIDE_SLUGS) {
        all.push(entry(\`\${SITE_URL}/visa-checker/\${cs}/\${gs}\`, 0.6));
      }
    }
    urls = all.slice(n * CHUNK_SIZE, (n + 1) * CHUNK_SIZE);
  }

  if (!urls.length) {
    return new NextResponse("<!-- empty chunk -->", {
      status: 404,
      headers: { "Content-Type": "application/xml" },
    });
  }

  return new NextResponse(buildXml(urls), {
    headers: { "Content-Type": "application/xml" },
  });
}
`;
write(path.join(SITEMAP_DIR, "_shared.js"), shared);

// ── 3. app/sitemap/static/route.js ───────────────────────────────────────────
const staticRoute = `// app/sitemap/static/route.js — Auto-generated
import { handleChunk } from "../_shared";
export const dynamic    = "force-dynamic";
export const runtime    = "nodejs";
export const maxDuration = 60;
export const GET = () => handleChunk("static");
`;
write(path.join(SITEMAP_DIR, "static", "route.js"), staticRoute);

// ── 4. pairs-N route files ────────────────────────────────────────────────────
for (const n of PAIR_CHUNKS) {
  const content = `// app/sitemap/pairs-${n}/route.js — Auto-generated
import { handleChunk } from "../_shared";
export const dynamic     = "force-dynamic";
export const runtime     = "nodejs";
export const maxDuration = 60;
export const GET = () => handleChunk("pairs-${n}");
`;
  write(path.join(SITEMAP_DIR, `pairs-${n}`, "route.js"), content);
}

// ── 5. guides-N route files ───────────────────────────────────────────────────
for (const n of GUIDE_CHUNKS) {
  const content = `// app/sitemap/guides-${n}/route.js — Auto-generated
import { handleChunk } from "../_shared";
export const dynamic     = "force-dynamic";
export const runtime     = "nodejs";
export const maxDuration = 60;
export const GET = () => handleChunk("guides-${n}");
`;
  write(path.join(SITEMAP_DIR, `guides-${n}`, "route.js"), content);
}

// ── Done ──────────────────────────────────────────────────────────────────────
console.log("\n✅ Sitemap files generated successfully!");
console.log("\nURLs after generation:");
console.log("  /sitemap.xml            → sitemap index");
console.log("  /sitemap/static         → static pages");
console.log("  /sitemap/pairs-0        → country pairs chunk 1");
console.log("  /sitemap/pairs-1        → country pairs chunk 2");
console.log("  /sitemap/guides-0       → guide pages chunk 1");
console.log("  /sitemap/guides-1       → guide pages chunk 2");
console.log("  ... up to guides-8");
console.log("\nTotal: ~475,000 URLs across 12 sitemaps");
